# Helm resource file for the MC project,
# declaring part of the MC application in a cluster.
# Â© Copyright Benedict Adamson 2019.
#
# This file is part of MC.
#
# MC is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# MC is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with MC.  If not, see <https://www.gnu.org/licenses/>.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mc-http-deploy
  labels:
{{ include "mc.labels" . | indent 4 }}
  app.kubernetes.io/component: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mc.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      -  name: mc-front-end
         image: benedictadamson/mc-front-end:2.0.1-SNAPSHOT
         ports:
         -  containerPort: 80
            name: http
         volumeMounts:
         -  mountPath: /config
            name: mc-fe-config
            readOnly: true
         livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 13
      volumes:
      -  name: mc-fe-config
         configMap:
           name: mc-fe-config